# Generated by Django 6.0.4 on 2026-06-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstart',
            old_name='email',
            new_name='contact',
        ),
    ]
