# Generated by Django 6.0.4 on 2026-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(default='Краткое описание', max_length=200, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Текст о проекте')),
                ('image', models.ImageField(default='progect_photos/default.png', upload_to='project_photos/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
