# Generated by Django 6.0.4 on 2026-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Тут должно быть описание', max_length=200, verbose_name='Описание'),
        ),
    ]
