# Generated by Django 6.0.4 on 2026-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_photos/default.png', upload_to='blog_photos/', verbose_name='Фотография'),
        ),
    ]
