# Generated by Django 6.0.4 on 2026-06-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_categoryname_alter_post_options_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blogapp.categoryname', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
